### ISSUE TITLE
Cart Code Issue

### ISSUE THREAD

**Issue by AlanDogg** [shshanker/woo-floating-minicart#1]
Hi,
I have noticed in the Woo Floating Minicart that when I ad an item to it I get 2 pieces of code inbetween the Cart & Checkout buttons (See pic attachments), when I navigate to another page then back it corrects itself. Any ideas?

Many thanks

![just added to cart](https://cloud.githubusercontent.com/assets/18066629/14040429/22dfb1c2-f25f-11e5-862c-de4f32cba320.png)
![page refreshed](https://cloud.githubusercontent.com/assets/18066629/14040432/2b95f808-f25f-11e5-926f-f423cfc9a26f.png)

**Comment by shivashankerbhatta** [comment]
Thanks for contacting us,
As we'd tested on number of other themes, we could not reflect issues like
that, would you please forward the link so that we could figure out the
exact causes.

*Sincerely, *

**Comment by AlanDogg** [comment]
www.fixtronic.co.uk/main

**Comment by shivashankerbhatta** [comment]
Hello there,
That is not a plugin issue, there's a button class named "wc-forward", which decorates the arrow through your site css, would you please inspect and fix the issue with help of UI/UX expert.

**Comment by AlanDogg** [comment]
Its a blip I can live with for now :)
