### ISSUE TITLE
Floating Minicart missing option to show cart when empty

### ISSUE THREAD

**Issue by SeattleNewMedia** [shshanker/woo-floating-minicart#2]
I find it undesirable from a business perspective to not show the cart at all times.  I think it encourages users to want to put something in their cart if they see that it is empty.  Not always of course.  But it should at least be an option from the Settings page to allow for this.  Just a simple checkbox would work.  It looks like the woo-floating-minicart just does not show content for "0" items and "Your cart is empty".  It's not that the cart is there suppressed.  Could someone please add this in as an option in Settings?  Thanks.

**Comment by shivashankerbhatta** [comment]
This facilities have been added on "https://wordpress.org/plugins/woo-floating-minicart/". Would you please update the plugin to the latest release?
