### ISSUE TITLE
Plugin is generating errors in the error_log

### ISSUE THREAD

**Issue by dlfdlf56** [shshanker/woo-floating-minicart#3]
This error appears to be coming from woo-floating-minicart/includes/awfm-frontend.php
The WC_Cart::get_checkout_url function is deprecated since version 2.5. Replace with wc_get_checkout_url.

**Comment by shivashankerbhatta** [comment]
This issues have been solve on "https://wordpress.org/plugins/woo-floating-minicart/". Would you please update the plugin to the latest release?
